# ServerProperties
server:
  port: 8080
  #访问根
  servlet:
    context-path: /management


# DataSourceProperties
spring:
  profiles:
    active: local           #开发环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${project.db.host}:3306/file_management?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ${project.db.pw}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      idle-timeout: 30000
      minimum-idle: 5
    # Redis配置,选用4号库
  redis:
    database: 4
    host: 192.168.136.100
    port: 6379
    password: 123456

# MybatisPlusProperties
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.file_management.project.entity
  configuration:
    # 自动生成id
    useGeneratedKeys: true
    mapUnderscoreToCamelCase: true

# logger
#在类中声明一个logger就会自动把这个类的日志信息记录到配置文件，logback.xml里设置的地址文件中
logging:
  level:
    com.file_management.project: debug

#文件存储位置
#file:${user.dir}代表的位置是工程根目录下。
file:
  upload:
    dir: ${user.dir}/upload


# 自由配置
fileManagement:
  #访问路径
  path:
    #domain: http://127.0.0.1:8080
    #upload: d:/01-document/01-Project/upload


